export type {
  ResolvedSceneArea,
  ResolvedSceneObject,
  ResolvedScenePlatform,
  ResolvedSceneTile,
  SceneArea,
  SceneAreaCurve,
  SceneAreaDefaults,
  SceneAreaVertex,
  SceneBehaviorAreaAttribute,
  SceneBehaviorAreaLikeAttribute,
  SceneBehaviorAttribute,
  SceneBehaviorAttributeOverride,
  SceneBehaviorDefinition,
  SceneBehaviorInstance,
  SceneBehaviorNumberAttribute,
  SceneBehaviorNumberDefaults,
  SceneBehaviorObjectAttribute,
  SceneBehaviorPlatformAttribute,
  SceneDesignerCanvasConfig,
  SceneDesignerConfig,
  SceneDesignerGridConfig,
  SceneDesignerKeyboardConfig,
  SceneDefinition,
  SceneDesignerManifest,
  SceneDesignerMouseConfig,
  SceneDesignerNudgeConfig,
  SceneDesignerNudgeKeysConfig,
  SceneDesignerShortcutModifier,
  SceneLayer,
  SceneObject,
  SceneObjectDefaults,
  ScenePlatform,
  ScenePlatformDefaults,
  ScenePlatformFitPaint,
  ScenePlatformPaint,
  ScenePlatformTilePaint,
  ScenePlatformTileMapPaint,
  SceneTileDefinition,
  SceneTileMapCell,
  SceneTileProperty,
  SceneTileRotation,
  SceneTileSetDefinition,
  SceneSelection
} from "./types.js";

export {
  assertArea,
  assertBehavior,
  assertBehaviorAttribute,
  assertBehaviorInstance,
  assertLayer,
  assertObject,
  assertScene,
  assertSceneManifest,
  assertTileSet,
  behaviorAttributeId,
  behaviorInstanceIdFromAttributeId,
  cloneSceneManifest,
  defineScene,
  defineSceneManifest,
  defineScenes,
  ensureBehaviorOverride,
  getScene,
  getTileSet,
  isScenePlatform,
  resolveSceneArea,
  resolveSceneObject,
  resolveBehaviorNumber,
  resolveScenePlatform,
  sceneAreas,
  sceneLayerAreas,
  sceneLayerObjects,
  sceneLayerPlatforms,
  sceneObjects,
  scenePlatforms,
  sceneTileMaps,
  sceneTiles,
  sceneTilesAt
} from "./manifest.js";

export {
  createArea,
  createAreaVertex,
  createBehavior,
  createBehaviorAreaAttribute,
  createBehaviorInstance,
  createBehaviorNumberAttribute,
  createBehaviorObjectAttribute,
  createBehaviorPlatformAttribute,
  createLayer,
  createObject,
  createPlatform,
  createScene,
  createTileMapCell,
  duplicateObject,
  uniqueId
} from "./factories.js";

export type {
  CreateAreaInput,
  CreateBehaviorInput,
  CreateBehaviorInstanceInput,
  CreateLayerInput,
  CreateObjectInput,
  CreatePlatformInput,
  CreateSceneInput,
  CreateTileMapCellInput
} from "./factories.js";
