export type {
  ResolvedSceneArea,
  ResolvedSceneObject,
  ResolvedScenePlatform,
  SceneArea,
  SceneAreaCurve,
  SceneAreaDefaults,
  SceneAreaVertex,
  SceneBehaviorAreaAttribute,
  SceneBehaviorAreaLikeAttribute,
  SceneBehaviorAttribute,
  SceneBehaviorAttributeOverride,
  SceneBehaviorDefinition,
  SceneBehaviorInstance,
  SceneBehaviorNumberAttribute,
  SceneBehaviorNumberDefaults,
  SceneBehaviorObjectAttribute,
  SceneBehaviorPlatformAttribute,
  SceneDesignerCanvasConfig,
  SceneDesignerConfig,
  SceneDesignerGridConfig,
  SceneDesignerKeyboardConfig,
  SceneDefinition,
  SceneDesignerManifest,
  SceneDesignerMouseConfig,
  SceneDesignerNudgeConfig,
  SceneDesignerNudgeKeysConfig,
  SceneDesignerShortcutModifier,
  SceneLayer,
  SceneObject,
  SceneObjectDefaults,
  ScenePlatform,
  ScenePlatformDefaults,
  ScenePlatformFitPaint,
  ScenePlatformPaint,
  ScenePlatformTilePaint,
  SceneSelection
} from "./types.js";

export {
  assertArea,
  assertBehavior,
  assertBehaviorAttribute,
  assertBehaviorInstance,
  assertLayer,
  assertObject,
  assertScene,
  assertSceneManifest,
  behaviorAttributeId,
  behaviorInstanceIdFromAttributeId,
  cloneSceneManifest,
  defineScene,
  defineSceneManifest,
  defineScenes,
  ensureBehaviorOverride,
  getScene,
  resolveSceneArea,
  resolveSceneObject,
  resolveBehaviorNumber,
  resolveScenePlatform,
  sceneAreas,
  sceneLayerAreas,
  sceneLayerObjects,
  sceneLayerPlatforms,
  sceneObjects,
  scenePlatforms
} from "./manifest.js";

export {
  createArea,
  createAreaVertex,
  createBehavior,
  createBehaviorAreaAttribute,
  createBehaviorInstance,
  createBehaviorNumberAttribute,
  createBehaviorObjectAttribute,
  createBehaviorPlatformAttribute,
  createLayer,
  createObject,
  createPlatform,
  createScene,
  duplicateObject,
  uniqueId
} from "./factories.js";

export type {
  CreateAreaInput,
  CreateBehaviorInput,
  CreateBehaviorInstanceInput,
  CreateLayerInput,
  CreateObjectInput,
  CreatePlatformInput,
  CreateSceneInput
} from "./factories.js";
